<!doctype html>
<html lang="ru">
	<head>
		<meta charset="utf-8">
		<title>Sciendar</title> 
		<meta name="description" content="Конференции,научние достижения,собрания статей">
		<meta name="robots" content="noindex, nofollow">  
		<meta name="viewport" content="width=device-width,initial-scale=1.0">
		<link rel="SHORTCUT ICON" href="/public/img/global/icon/favicon.png" type="image/png">
		<link rel="stylesheet" type="text/css" href="/public/css/reset.css">
		<link rel="stylesheet prefetch" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
		<link rel="stylesheet" type="text/css" href="/public/css/main.css"> 
		<link rel="stylesheet" type="text/css" href="/public/css/front/front.css?555"> 
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
		<script type="text/javascript" src="/public/js/front/jq_front.js"></script>
		<!--[if lt IE 9]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
		<body>	
		<div id=wrapPage>		
			<header id="mainHeader">
				<h1>Sciendar</h1>
				<nav id="navTop">
					<ul>
						<a href="#win1" class="button button-green"><li class="sprLogin"></li></a>
						<li class="sprLogin"></li>
						<li class="sprLogin"></li>
					</ul>
					 <a href="#x" class="overlay" id="win1"></a>
					<div class="popup">
        <form class="login">
  
  <fieldset>
    
  	<legend class="legend">Login</legend>
    
    <div class="input">
    	<input type="email" placeholder="Email" required />
      <span><i class="fa fa-envelope-o"></i></span>
    </div>
    
    <div class="input">
    	<input type="password" placeholder="Password" required />
      <span><i class="fa fa-lock"></i></span>
    </div>
    
    <button type="submit" class="submit"><i class="fa fa-long-arrow-right"></i></button>
    
  </fieldset>
  
  <div class="feedback">
  	login successful <br />
    redirecting...
  </div>
  
</form>
    <a class="close" title="Закрыть" href="#close"></a>
    </div>
					<a href="#x" class="overlay" id="win2"></a>
   <div class="popup">
     					<form  onsubmit="return false;">
					<fieldset class="fdtTyEvent">
    					<legend>Типы событий и их характеристики</legend>
    					<span>Научных мераприятий выбранно</span><button>выбранно:0</button>
						<div>
							<input type="checkbox" name="option2" value="a2">Windows 2000<Br>
							<input type="checkbox" name="option3" value="a3">System X<Br> 
							<input type="checkbox" name="option4" value="a4">Linux<Br> 
							<input type="checkbox" name="option5" value="a5">X3-DOSss</p>
						</div>
    				</fieldset>		
    				<fieldset>
    					<legend>Место и время я язык</legend>			
						<select name="select2">
							<option selected="selected" disabled >Выберите героя</option>
							<optgroup selected="selected" label="Зелень">
								<option>Крокодил Гена</option>
								<option>Чебурашка ниндзя</option>
							</optgroup>
							<optgroup  label="Красные">
								<option>Индеец</option>
								<option>Демон</option>
								<option>Крыса Лариса</option>
							</optgroup>
						</select>
					</fieldset>		
					</form>
    <a class="close"title="Закрыть" href="#close"></a>
    </div>
				</nav>
				<img src="https://basicvntls.files.wordpress.com/2012/12/cropped-resized.jpg" title="Логотип Sciendar" alt="Альтернативный текст для изображения.">				
				<a href="#win2" class="button button-red">Задать параметры поиска конференций</a>
			
			</header> 			
				<main>
						<?=$content ?>  
				</main> 
			</div>		
			<footer id="mainFooter">				
					<p>©2008-2016 Sciendar</p>
					<p>Тел. +xx(xxxx) xx-xx-xx, Факс: +xx(xxxx) xx-xx-xx.</p>
					<p>Приймальна комісія: тел/факс: +xx(xxxx) xx-xx-xx</p>
					<p>e-mail: xxxxxx@xxxxx.xxx.xx</p>
			</footer>	

		</body>
</html>



<!--	   

		

		<script type="text/javascript" src="/public/js/jQuery-v1.8.2.js"></script>
		<script type="text/javascript" src="/public/js/front/jquery.easing.1.3.js"></script>
		<script type="text/javascript" src="/public/js/jquery.cookie.js"></script>
		<script type="text/javascript" src="/public/js/front/jq_front.js"></script>
		<script type="text/javascript" src="/public/js/front/mu_jq_main.js"></script>
		<script type="text/javascript" src="/public/js/jq_main.js"></script>
		<script type="text/javascript" src="/public/js/Hurl.js"></script>
		<script type="text/javascript" src="/public/js/front/jquery.slider.js"></script>
		<script src="/public/js/front/liteaccordion.jquery.js"></script>
		<script type="text/javascript" src="/public/js/front/jquery.tmpl.min.js"></script>		
		<script type="text/javascript" src="/public/js/front/jquery.elastislide.js"></script>
		<script type="text/javascript" src="/public/js/front/gallery.js"></script>
		<script type="text/javascript" src="/public/js/jquery-ui.js"></script>
		-->