<?php 



if(!empty($content)){
foreach ($content as $key => $value) {	
		echo $value['content'];
	}
}else{

	?>	
<header class="">			
						<h2>Активные научные программы</h2>
					</header>	
					<article>
						<div class="headerConf">							
							<p>2016-10-26</p>
							<span class="sprKonf"></span>
							<span class="sprKonf"></span>	
							<span class="sprKonf"></span>	
							<span class="sprKonf"></span>											
						</div>							
						<article class="confInfo">
							<h3>Конфа няшек</h3>
								<p>Они уже мертвы их остывшие тела осих остывшие тела останутся гнитих остывшие тела останутся гниттанутся 	гних остывшие тела останутся гнититих остывшие тела останутся гнить на этом поле боя навсегда….</p>
						</article>	
							<img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQoxzDY5d8XQrf65iI1WW243k28MOd3Jv1ZLUL5Rs69jBzbM5C9" title="Конфа няшек" alt="Альтернативный текст для изображения.">	
					</article>
					<article>
						<div class="headerConf">							
							<p>2016-10-26</p>
							<span class="sprKonf"></span>
							<span class="sprKonf"></span>	
							<span class="sprKonf"></span>	
							<span class="sprKonf"></span>											
						</div>							
						<article class="confInfo">
							<h3>Конфа няшек</h3>
								<p>Они уже мертвы их остывшие тела осих остывшие тела останутся гнитих остывшие тела останутся гниттанутся 	гних остывшие тела останутся гнититих остывшие тела останутся гнить на этом поле боя навсегда….</p>
						</article>		
							<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOwBtMzu97aTEN_zgtBLiQIh4vYxKUYAGqKZubK-4acFY4DPjm" title="Конфа феритейл" alt="Альтернативный текст для изображения.">												
					</article>
					<article>
						<div class="headerConf">							
							<p>2016-10-26</p>
							<span class="sprKonf"></span>
							<span class="sprKonf"></span>	
							<span class="sprKonf"></span>	
							<span class="sprKonf"></span>											
						</div>							
						<article class="confInfo">
							<h3>Конфа няшек</h3>
								<p>Они уже мертвы их остывшие тела осих остывшие тела останутся гнитих остывшие тела останутся гниттанутся 	гних остывшие тела останутся гнититих остывшие тела останутся гнить на этом поле боя навсегда….</p>
						</article>		
							<img src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS1SB3Ogn_2jmGc5TZpYBqtKN0v4m_J5AyMCYNjGfH9qj7LiHwu_A" title="Облачная конференция" alt="Альтернативный текст для изображения.">														
					</article>
					<article>
						<div class="headerConf">							
							<p>2016-10-26</p>
							<span class="sprKonf"></span>
							<span class="sprKonf"></span>	
							<span class="sprKonf"></span>	
							<span class="sprKonf"></span>											
						</div>							
						<article class="confInfo">
							<h3>Конфа няшек</h3>
								<p>Они уже мертвы их остывшие тела осих остывшие тела останутся гнитих остывшие тела останутся гниттанутся 	гних остывшие тела останутся гнититих остывшие тела останутся гнить на этом поле боя навсегда….</p>
						</article>					
							<img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQoxzDY5d8XQrf65iI1WW243k28MOd3Jv1ZLUL5Rs69jBzbM5C9" title="Конфа няшек" alt="Альтернативный текст для изображения.">														
					</article>
					<article>
						<div class="headerConf">							
							<p>2016-10-26</p>
							<span class="sprKonf"></span>
							<span class="sprKonf"></span>	
							<span class="sprKonf"></span>	
							<span class="sprKonf"></span>											
						</div>							
						<article class="confInfo">
							<h3>Конфа няшек</h3>
								<p>Они уже мертвы их остывшие тела осих остывшие тела останутся гнитих остывшие тела останутся гниттанутся 	гних остывшие тела останутся гнититих остывшие тела останутся гнить на этом поле боя навсегда….</p>
						</article>							
							<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOwBtMzu97aTEN_zgtBLiQIh4vYxKUYAGqKZubK-4acFY4DPjm" title="Конфа феритейл" alt="Альтернативный текст для изображения.">													
					</article>
					<article>
						<div class="headerConf">							
							<p>2016-10-26</p>
							<span class="sprKonf"></span>
							<span class="sprKonf"></span>	
							<span class="sprKonf"></span>	
							<span class="sprKonf"></span>											
						</div>							
						<article class="confInfo">
							<h3>Конфа няшек</h3>
								<p>Они уже мертвы их остывшие тела осих остывшие тела останутся гнитих остывшие тела останутся гниттанутся 	гних остывшие тела останутся гнититих остывшие тела останутся гнить на этом поле боя навсегда….</p>
						</article>				
						<img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSFvBq18WjJMiuM2zGMlza8k1Jjze6BIsIDjoUbzNH2IMS50NMd" title="Ветеренар конференция" alt="Альтернативный текст для изображения.">										
					</article>				

<?php
	}
?>